apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - image: bitnami/redis:3.2.8-r1
        name: redis
        volumeMounts:
        - mountPath: /bitnami/redis
          name: redis-data
      - image: oliver006/redis_exporter
        name: exporter
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PASSWORD
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvd-claim
