kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-nas
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  volumeName: prometheus-nas
  
