apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flower
  namespace: flower
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "flower.xiaolumm.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: xiaolusys-flower
          servicePort: 5555
